{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.invlib.kyungmin08g",
    "module": "invlib-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "invlib-api-1.0.0.jar",
          "url": "invlib-api-1.0.0.jar",
          "size": 18698,
          "sha512": "2df95ac9430a8a60a7ebf98de9bb5b838093a8a6376ef8b65f0a1913c9629fe4d3e06b76909ed7b29d1af0ac30636a7237489aa0bcd41bb68e50e7d08463c4b1",
          "sha256": "7251ff0fd1391e064fa2032e315dd185423684d3a5fad9849f078fb7718c9136",
          "sha1": "94ab157c54cfd90fcee3508a6629ea0b6c29a642",
          "md5": "b9e61a597325618c6e21513e4df32f99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "invlib-api-1.0.0.jar",
          "url": "invlib-api-1.0.0.jar",
          "size": 18698,
          "sha512": "2df95ac9430a8a60a7ebf98de9bb5b838093a8a6376ef8b65f0a1913c9629fe4d3e06b76909ed7b29d1af0ac30636a7237489aa0bcd41bb68e50e7d08463c4b1",
          "sha256": "7251ff0fd1391e064fa2032e315dd185423684d3a5fad9849f078fb7718c9136",
          "sha1": "94ab157c54cfd90fcee3508a6629ea0b6c29a642",
          "md5": "b9e61a597325618c6e21513e4df32f99"
        }
      ]
    }
  ]
}
