{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.invlib.kyungmin08g",
    "module": "invlib-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "invlib-api-1.0.0.jar",
          "url": "invlib-api-1.0.0.jar",
          "size": 18545,
          "sha512": "ba79bfade266b2f8ae8c71708aa4eb21ba268b8567f913a4af8d1f2edaf0f5fbb91d9f16e88e553d54846ad1349d1000d4b401a661219f688ad1f8ff9213d601",
          "sha256": "81d89385c30aad70f4684a26cb819652bdc4f4fef762971744186a5c477e0239",
          "sha1": "5d1fc56322c49a7d85b269ca2d5907ff3b547508",
          "md5": "6875db91cea567899d5021ae6d17dd7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "invlib-api-1.0.0.jar",
          "url": "invlib-api-1.0.0.jar",
          "size": 18545,
          "sha512": "ba79bfade266b2f8ae8c71708aa4eb21ba268b8567f913a4af8d1f2edaf0f5fbb91d9f16e88e553d54846ad1349d1000d4b401a661219f688ad1f8ff9213d601",
          "sha256": "81d89385c30aad70f4684a26cb819652bdc4f4fef762971744186a5c477e0239",
          "sha1": "5d1fc56322c49a7d85b269ca2d5907ff3b547508",
          "md5": "6875db91cea567899d5021ae6d17dd7f"
        }
      ]
    }
  ]
}
